# -*- coding: utf-8 -*-
"""Data_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/156LGp2iyXgzypwZD9FhP9nYjJS31hS99
"""

import requests

CLIENT_ID = "1000.ZR1LQT5PK4B2RPU0YL6H2KE5A4RZDU"
CLIENT_SECRET = "ecce01ec8b3a21fc991a9e2f4c9d425a6e42957174"
REFRESH_TOKEN = "1000.6adb77f6f7493307d29a07e1cded7cfb.bb226b75b1713a764f7669af29efab17"

def generate_access_token():
    url = "https://accounts.zoho.com/oauth/v2/token"
    data = {
        "refresh_token": REFRESH_TOKEN,
        "client_id": CLIENT_ID,
        "client_secret": CLIENT_SECRET,
        "grant_type": "refresh_token"
    }
    response = requests.post(url, data=data)
    result = response.json()
    if "access_token" in result:
        print("✅ Access token generated successfully!")
        return result["access_token"]
    else:
        print("❌ Error generating access token:", result)
        return None

access_token = generate_access_token()
print("Access Token:", access_token)

import pandas as pd
import numpy as np
import re
from sqlalchemy import create_engine
import requests # Added for fetching tickets

# ==============================
# CONFIG (from previous cells)
# ==============================
CLIENT_ID = "1000.ZR1LQT5PK4B2RPU0YL6H2KE5A4RZDU"
CLIENT_SECRET = "ecce01ec8b3a21fc991a9e2f4c9d425a6e42957174"
REFRESH_TOKEN = "1000.6adb77f6f7493307d29a07e1cded7cfb.bb226b75b1713a764f7669af29efab17" # Use the latest refresh token
ORG_ID = "742973684"
DATABASE_PATH = "zoho_tickets.db"

# ==============================
# STEP 1: GENERATE ACCESS TOKEN
# ==============================
def generate_access_token(refresh_token, client_id, client_secret):
    url = "https://accounts.zoho.com/oauth/v2/token"
    data = {
        "refresh_token": refresh_token,
        "client_id": client_id,
        "client_secret": client_secret,
        "grant_type": "refresh_token"
    }
    response = requests.post(url, data=data)
    result = response.json()
    if "access_token" in result:
        print("✅ Access token generated successfully!")
        return result["access_token"]
    else:
        print("❌ Error generating access token:", result)
        return None

ACCESS_TOKEN = generate_access_token(REFRESH_TOKEN, CLIENT_ID, CLIENT_SECRET)

if not ACCESS_TOKEN:
    print("Failed to obtain access token. Aborting ticket fetching.")
else:
    # ==============================
    # FETCH TICKETS (integrated from previous step)
    # ==============================
    url = "https://desk.zoho.com/api/v1/tickets"
    headers = {
        "Authorization": f"Zoho-oauthtoken {ACCESS_TOKEN}",
        "orgId": ORG_ID
    }

    tickets = []
    start = 0
    while True:
        params = {"limit": 100, "from": start}
        response = requests.get(url, headers=headers, params=params)
        if response.status_code != 200:
            print("Error fetching tickets:", response.status_code, response.text)
            break
        if response.status_code == 204:  # No content
            print("No more tickets to fetch.")
            break
        data = response.json()
        if not data.get("data"):
            break
        tickets.extend(data["data"])
        start += 100

    # ==============================
    # NORMALIZE & SELECT COLUMNS & SAVE TO DB (integrated from previous step)
    # ==============================
    engine = create_engine(f"sqlite:///{DATABASE_PATH}") # Initialize engine

    if tickets:
        df_fetched = pd.json_normalize(tickets)

        # Select only columns that exist
        columns_to_keep = [
            "id",
            "ticketNumber",
            "subject",
            "status",
            "priority",
            "contact.name",
            "contact.email",
            "department.name",
            "createdTime",
            "modifiedTime"
        ]
        existing_columns = [col for col in columns_to_keep if col in df_fetched.columns]
        df_fetched = df_fetched[existing_columns]

        # Categorize tickets (optional, for output)
        df_open = df_fetched[df_fetched["status"] == "Open"] if "status" in df_fetched.columns else pd.DataFrame()
        df_closed = df_fetched[df_fetched["status"] == "Closed"] if "status" in df_fetched.columns else pd.DataFrame()
        print(f"Open Tickets: {len(df_open)}")
        print(f"Closed Tickets: {len(df_closed)}")

        # Save to database
        df_fetched.to_sql("tickets", con=engine, if_exists="replace", index=False)
        print(f"Saved {len(df_fetched)} tickets to '{DATABASE_PATH}'")
    else:
        print("No tickets found to save.")

    # ==============================
    # LOAD AND PREPROCESS (original intent of this cell)
    # ==============================
    # Load the DataFrame from the database now that it's guaranteed to be there
    df = pd.read_sql("SELECT * FROM tickets", con=engine)

    # 1️⃣ Select relevant columns
    columns_needed = [
        "id", "ticketNumber", "subject", "status", "priority",
        "createdTime", "modifiedTime"
    ]

    # Keep only existing columns
    columns_existing = [col for col in columns_needed if col in df.columns]
    df = df[columns_existing]

    # 2️⃣ Handle missing values
    df.fillna({"priority": "Normal", "status": "Open", "subject": ""}, inplace=True)

    # 3️⃣ Convert timestamps to datetime
    df["createdTime"] = pd.to_datetime(df["createdTime"], errors="coerce")
    if "modifiedTime" in df.columns:
        df["modifiedTime"] = pd.to_datetime(df["modifiedTime"], errors="coerce")

    # 4️⃣ Clean text columns (lowercase, remove extra spaces)
    def clean_text(text):
        if not isinstance(text, str):
            return ""
        text = text.lower()
        text = re.sub(r"\s+", " ", text)  # Replace multiple spaces with one
        text = text.strip()
        return text

    df["subject_clean"] = df["subject"].apply(clean_text)

    # Optional: Generate basic features for ML
    df["subject_length"] = df["subject_clean"].apply(len)
    df["is_closed"] = df["status"].apply(lambda x: 1 if x.lower() == "closed" else 0)

    # 5️⃣ Preview preprocessed data
    print("Preprocessed Tickets Sample:")
    print(df.head())

    # 6️⃣ Save to CSV or database for AI/ML integration
    df.to_csv("preprocessed_zoho_tickets.csv", index=False)
    print("Preprocessed dataset saved as 'preprocessed_zoho_tickets.csv'")

# ==============================
# 1. Import Libraries
# ==============================

import pandas as pd
import re
import matplotlib.pyplot as plt
from sentence_transformers import SentenceTransformer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from collections import Counter


# ==============================
# 2. Load Dataset
# ==============================

df = pd.read_csv("preprocessed_zoho_tickets.csv")

df['subject'] = df['subject'].astype(str)
df['createdTime'] = pd.to_datetime(df['createdTime'])


# ==============================
# 3. Clean Subject Lines
# ==============================

def clean_text(text):

    text = text.lower()

    # remove email prefixes
    text = re.sub(r"re:|fwd:|fw:", "", text)

    # remove special characters
    text = re.sub(r"[^a-z\s]", "", text)

    # remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text


df['clean_subject'] = df['subject'].apply(clean_text)


# ==============================
# 4. Load AI Semantic Model
# ==============================

print("Loading AI model...")

model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')


# ==============================
# 5. Convert Subjects to Embeddings
# ==============================

print("Converting subjects to embeddings...")

embeddings = model.encode(df['clean_subject'], show_progress_bar=True)


# ==============================
# 6. Automatically Find Best Number of Clusters
# ==============================

print("Finding optimal number of clusters...")

best_k = 2
best_score = -1

for k in range(2,10):

    kmeans = KMeans(n_clusters=k, random_state=42)

    labels = kmeans.fit_predict(embeddings)

    score = silhouette_score(embeddings, labels)

    if score > best_score:

        best_k = k
        best_score = score


print("Best number of clusters:", best_k)


# ==============================
# 7. Final Clustering
# ==============================

kmeans = KMeans(n_clusters=best_k, random_state=42)

df['cluster'] = kmeans.fit_predict(embeddings)


# ==============================
# 8. Generate Issue Names
# ==============================

issue_labels = {}

for cluster_id in range(best_k):

    cluster_text = " ".join(df[df['cluster']==cluster_id]['clean_subject'])

    words = cluster_text.split()

    common_words = [w for w,_ in Counter(words).most_common(3)]

    label = " ".join(common_words).title()

    issue_labels[cluster_id] = label


df['issue_name'] = df['cluster'].map(issue_labels)


# ==============================
# 9. Issue Summary
# ==============================

summary = df.groupby('issue_name').agg(

    ticket_count=('subject','count'),

    first_ticket=('createdTime','min'),

    last_ticket=('createdTime','max')

).sort_values(by='ticket_count', ascending=False)


print("\n==============================")
print("ISSUE SUMMARY")
print("==============================\n")

print(summary)


# ==============================
# 10. Most Occurring Issue
# ==============================

top_issue = summary.index[0]

top_count = summary.iloc[0]['ticket_count']

print("\nMost Occurring Issue:", top_issue)

print("Number of Tickets:", top_count)


# ==============================
# 11. Issue Trends Over Time
# ==============================

df['date'] = df['createdTime'].dt.date

trend = df.groupby(['date','issue_name']).size().unstack(fill_value=0)

print("\n==============================")
print("ISSUE TREND TABLE")
print("==============================\n")

print(trend)


# ==============================
# 12. Plot Issue Trends
# ==============================

trend.plot(figsize=(12,6))

plt.title("Support Ticket Issues Over Time")

plt.xlabel("Date")

plt.ylabel("Number of Tickets")

plt.legend(title="Issue")

plt.tight_layout()

plt.show()

# =====================================
# 1. Import Required Libraries
# =====================================

import pandas as pd
import re
import matplotlib.pyplot as plt
from sentence_transformers import SentenceTransformer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from collections import Counter


# =====================================
# 2. Load Dataset
# =====================================

print("Loading dataset...")

df = pd.read_csv("preprocessed_zoho_tickets.csv")

# Ensure correct data types
df["subject"] = df["subject"].astype(str)
df["createdTime"] = pd.to_datetime(df["createdTime"])

print("Total tickets loaded:", len(df))


# =====================================
# 3. Clean Ticket Subject Text
# =====================================

def clean_text(text):

    text = text.lower()

    # Remove email prefixes
    text = re.sub(r"(re:|fw:|fwd:)", "", text)

    # Remove special characters and numbers
    text = re.sub(r"[^a-z\s]", "", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text


df["clean_subject"] = df["subject"].apply(clean_text)


# =====================================
# 4. Load Semantic AI Model
# =====================================

print("\nLoading AI model...")

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")


# =====================================
# 5. Convert Subjects to Embeddings
# =====================================

print("Generating embeddings...")

embeddings = model.encode(
    df["clean_subject"],
    show_progress_bar=True
)


# =====================================
# 6. Determine Optimal Cluster Count
# =====================================

print("\nFinding optimal number of clusters...")

best_k = 2
best_score = -1

for k in range(2, 10):

    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = kmeans.fit_predict(embeddings)

    score = silhouette_score(embeddings, labels)

    if score > best_score:
        best_k = k
        best_score = score

print("Best number of clusters:", best_k)


# =====================================
# 7. Perform Final Clustering
# =====================================

print("\nClustering tickets...")

kmeans = KMeans(
    n_clusters=best_k,
    random_state=42,
    n_init=10
)

df["cluster"] = kmeans.fit_predict(embeddings)


# =====================================
# 8. Generate Issue Names
# =====================================

issue_labels = {}

for cluster_id in range(best_k):

    cluster_text = " ".join(
        df[df["cluster"] == cluster_id]["clean_subject"]
    )

    words = cluster_text.split()

    common_words = [
        w for w, _ in Counter(words).most_common(3)
    ]

    label = " ".join(common_words).title()

    issue_labels[cluster_id] = label

df["issue_name"] = df["cluster"].map(issue_labels)


# =====================================
# 9. Issue Summary
# =====================================

summary = (
    df.groupby("issue_name")
    .agg(
        ticket_count=("subject", "count"),
        first_ticket=("createdTime", "min"),
        last_ticket=("createdTime", "max")
    )
    .sort_values("ticket_count", ascending=False)
)

# Calculate percentages
summary["percentage"] = (
    summary["ticket_count"] /
    summary["ticket_count"].sum() * 100
).round(2)


print("\n==============================")
print("ISSUE SUMMARY")
print("==============================\n")

print(summary)


# =====================================
# 10. Total Tickets
# =====================================

total_tickets = summary["ticket_count"].sum()

print("\n==============================")
print("TOTAL TICKETS ANALYZED")
print("==============================")

print(total_tickets)


# =====================================
# 11. Most Frequent Issue
# =====================================

top_issue = summary.index[0]
top_count = summary.iloc[0]["ticket_count"]

print("\nMost Occurring Issue:", top_issue)
print("Number of Tickets:", top_count)


# =====================================
# 12. Issue Trends Over Time
# =====================================

df["date"] = df["createdTime"].dt.date

trend = (
    df.groupby(["date", "issue_name"])
    .size()
    .unstack(fill_value=0)
)

print("\n==============================")
print("ISSUE TREND TABLE")
print("==============================\n")

print(trend)


# =====================================
# 13. Plot Issue Trends
# =====================================

plt.figure(figsize=(12,6))

trend.plot()

plt.title("Support Ticket Issues Over Time")
plt.xlabel("Date")
plt.ylabel("Number of Tickets")
plt.legend(title="Issue")

plt.tight_layout()
plt.show()